<a href="https://colab.research.google.com/github/AkshayMetry/PyTorch-Learning/blob/main/00_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Resources

https://www.learnpytorch.io/00_pytorch_fundamentals/

##Pytorch Fundamentals

In [ ]:
#Pytorch Fundamentals
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#print(torch.__version__)

# Introduction To Tensor
 Creating tensors

In [ ]:
#scalars
#torch.Tensor - A torch.Tensor is a multi-dimensional matrix containing elements of a single data type.

scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
#Vector - Magnitude and direction
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
vector.ndim

1

In [ ]:
#MATRIX
MATRIX = torch.tensor([ [7,8],
                        [8,7] ])
MATRIX

tensor([[7, 8],
        [8, 7]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([8, 7])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [2,4,6]]])

TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [2, 4, 6]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [2, 4, 6]])

In [ ]:
TENSOR[0][1]

tensor([4, 5, 6])

##  Randoms Tensors

   Randoms tensors are imp because the way many neural network learn is that they start with tensors full of random numbers and then adjust those random numbers to bettter represent the data.

   Start with random number --> look at data --> update random numbers --> look at data --> update random numbers


 Create a random tensor of size
 https://pytorch.org/docs/stable/generated/torch.rand.html

In [ ]:

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0614, 0.6721, 0.4438, 0.6448],
        [0.1479, 0.6846, 0.5107, 0.8930],
        [0.6417, 0.1825, 0.3870, 0.5870]])

In [ ]:
random_tensor.shape

torch.Size([3, 4])

In [ ]:
random_tensor.ndim

2

In [ ]:
#Create a random tensor with similar shape to an image tensor
random_image_tensor = torch.rand(size=(3,224,224)) #height, width, color channel
random_image_tensor

tensor([[[0.5539, 0.7155, 0.3580,  ..., 0.3771, 0.1523, 0.3002],
         [0.9133, 0.8781, 0.4640,  ..., 0.5550, 0.2483, 0.1895],
         [0.0470, 0.1531, 0.1268,  ..., 0.9468, 0.8867, 0.6017],
         ...,
         [0.5805, 0.5175, 0.2832,  ..., 0.6577, 0.4492, 0.7977],
         [0.9514, 0.7141, 0.1532,  ..., 0.8774, 0.9594, 0.9520],
         [0.8280, 0.6680, 0.0338,  ..., 0.6945, 0.9273, 0.8067]],

        [[0.2726, 0.4069, 0.5811,  ..., 0.7633, 0.2121, 0.1498],
         [0.4270, 0.9864, 0.9006,  ..., 0.4120, 0.3502, 0.8413],
         [0.1719, 0.8764, 0.0109,  ..., 0.7185, 0.0600, 0.3966],
         ...,
         [0.0155, 0.9859, 0.2413,  ..., 0.5937, 0.5408, 0.1684],
         [0.6589, 0.4719, 0.1163,  ..., 0.2389, 0.4603, 0.1927],
         [0.4177, 0.5917, 0.4723,  ..., 0.3414, 0.2061, 0.9890]],

        [[0.0764, 0.1502, 0.3543,  ..., 0.8283, 0.8614, 0.9640],
         [0.2949, 0.5137, 0.5707,  ..., 0.4110, 0.3151, 0.7807],
         [0.3665, 0.3983, 0.8360,  ..., 0.6313, 0.2125, 0.

## Zero and Ones

In [ ]:

#Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
random_image_tensor.dtype

torch.float32

In [ ]:
# Creating a range of tensors and tensors-like
#Use torch.range()

one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#Creating tensors-like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensors datatypes
Note: Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [ ]:
# Tensors datatypes



# Float32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                                dtype = None, #what datatype is tensor - float32, float16
                                device = None, #what device is your tensor on
                                requires_grad=False) #whether or not to track gradients with tensors operation
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [ ]:
float_32_tensor = int_32_tensor

In [ ]:
#Getting information from tensors
# 1. Tensors not right datatype - to do get datatype from a tensors, can use tensor.dtype
# 2. Tensors not right shape - to get shape from a tensor, can use tensor.shape
# 3. Tensors not on the right device - to get device from a tensor, can use tensor.device

#Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.4081, 0.9372, 0.9668, 0.8421],
        [0.2283, 0.1646, 0.3181, 0.1371],
        [0.8343, 0.0345, 0.5111, 0.1364]])

In [ ]:
print(some_tensor)
print(f"Datatype of tensor:{some_tensor.dtype}")
print(f"Shape of tensor:{some_tensor.shape}")
print(f"Device of tensor:{some_tensor.device}")

tensor([[0.4081, 0.9372, 0.9668, 0.8421],
        [0.2283, 0.1646, 0.3181, 0.1371],
        [0.8343, 0.0345, 0.5111, 0.1364]])
Datatype of tensor:torch.float32
Shape of tensor:torch.Size([3, 4])
Device of tensor:cpu


## Manipulating Tensors (tensor operations)

1. Tensor operations include:
2. Addition
3. Substraction
4. Multiplication
5. Division
6. Matrix Multiplication

In [ ]:

#Create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
#Multiply 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
#Substract 10
tensor - 10

tensor([-9, -8, -7])

In [ ]:
#try out PyTorch in-built function
torch.mul(tensor,10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor,10)

tensor([11, 12, 13])

Matrix Multplciation
Two main ways of performing multiplication in neural network and deep learning:

1. Element-wise multiplication
2. Matrix Multiplication

1 . The **inner dimensions** must match:
  * `(3,2) @ (3,2)` wont work
  * `(2,3) @ (3,2)` will work
  * `(3,2) @ (2,3)` will work


2 . The resulting matrix has the shape of the **outer dimension**:
  * `(2,3) @ (3,2)` -> `(2,2)`
  * `(3,2) @ (2,3)` -> `(3,3)`


In [ ]:
torch.matmul(torch.rand(2,10),torch.rand(10,2))

tensor([[2.6686, 2.8938],
        [2.4284, 2.7266]])

In [ ]:
# Element wise multiplication
print(tensor,"*",tensor)
print(f"Equals:{tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:tensor([1, 4, 9])


In [ ]:
#Multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [ ]:
tensor @ tensor

tensor(14)

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 2.05 ms, sys: 0 ns, total: 2.05 ms
Wall time: 3.41 ms


In [ ]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 150 µs, sys: 0 ns, total: 150 µs
Wall time: 156 µs


tensor(14)

One of the most common errors in deep learning: shape errors

In [ ]:
#Shapes for matriz mutiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

torch.matmul(tensor_A,tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix our tensor shape issue, we can manipulate the shape of our tensors using **transpose**
A transpose switches the axes or dimensions of a given tensor.

In [ ]:
tensor_B,tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [ ]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes:tensor_A={tensor_A.shape},tensor_B={tensor_B.shape}")
print(f"New shapes:tensor_A={tensor_A.shape}(same as above),tensor_B.T={tensor_B.T.shape}")
print(f"Multiplying:{torch.matmul(tensor_A,tensor_B.T)}")
# torch.matmul(tensor_A,tensor_B.T)

Original shapes:tensor_A=torch.Size([3, 2]),tensor_B=torch.Size([3, 2])
New shapes:tensor_A=torch.Size([3, 2])(same as above),tensor_B.T=torch.Size([2, 3])
Multiplying:tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


## Finding the min, max, sum, etc (tensors aggregation)

In [ ]:
## Finding the min, max, sum, etc (tensors aggregation)
x = torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [ ]:
#Find min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
#Find max
torch.max(x), x.max(x)

(tensor(90), tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]))

In [ ]:
#Find the mean
#note : the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
#Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [ ]:
#Finding the positional min and max
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
#Find the position in tensor that has the minimum value with argmin() - > return index position tensor where minimum value occurs
x.argmin()

tensor(0)

In [ ]:
x[0]

tensor(0)

In [ ]:
#Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defines shape
* View - Return a view of an input tensor of ceratin shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimension permutted (swapped) in a certain way

In [ ]:
#Create a tensor
import torch
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
#Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#Changing z changes x(because a view of a tenspr share the same memory as the original tensor)
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
#Stack tensors in top of each other
x_stacked = torch.stack([x,x,x,x],dim=1)
x_stacked, x_stacked.shape

(tensor([[5., 5., 5., 5.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]]),
 torch.Size([9, 4]))

In [ ]:
# torch.squeeze() - removes all single dimensions form a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# remove extra dimensions from x_reshaped
x_squeeze = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeeze}")
print(f"New Shape: {x_squeeze.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New Shape: torch.Size([9])


In [ ]:
#torch.unsqueeze() - adds a single dimension to a target tensor ata specific dimension
print(f"Previous tensor: {x_squeeze}")
print(f"Previous shape: {x_squeeze.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeeze.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New Shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New Shape: torch.Size([1, 9])


In [ ]:
#torch.permute - rearranges the dimension of a target tensor
x_original = torch.rand(size=(224,224,3)) #[height, width, color_channel]
# x_original

#Permute the original tensor to rearrange the axis (or dim) order
x_permuted  = x_original.permute(2,0,1) # shift axis 0->1, 2->0, 1->2

print(f"Previous shape:{x_original.shape}")
print(f"New shape:{x_permuted.shape}")

x_permuted

Previous shape:torch.Size([224, 224, 3])
New shape:torch.Size([3, 224, 224])


tensor([[[0.9530, 0.8636, 0.0545,  ..., 0.8272, 0.7940, 0.7727],
         [0.8434, 0.3601, 0.7394,  ..., 0.0997, 0.2859, 0.9910],
         [0.0122, 0.9078, 0.3120,  ..., 0.9689, 0.2818, 0.9571],
         ...,
         [0.1144, 0.6784, 0.6683,  ..., 0.7441, 0.2382, 0.1264],
         [0.2641, 0.7304, 0.9241,  ..., 0.0289, 0.2059, 0.6758],
         [0.8757, 0.8648, 0.4037,  ..., 0.3898, 0.7086, 0.2216]],

        [[0.0247, 0.1323, 0.3262,  ..., 0.6657, 0.8480, 0.1725],
         [0.2033, 0.7893, 0.2255,  ..., 0.2252, 0.2165, 0.7144],
         [0.9078, 0.5588, 0.7796,  ..., 0.9058, 0.9866, 0.7814],
         ...,
         [0.7840, 0.5222, 0.1343,  ..., 0.1782, 0.4891, 0.8429],
         [0.0387, 0.7482, 0.8554,  ..., 0.1495, 0.4361, 0.7082],
         [0.1556, 0.3508, 0.9210,  ..., 0.5774, 0.5214, 0.1189]],

        [[0.6345, 0.0209, 0.4871,  ..., 0.1683, 0.3382, 0.9924],
         [0.7825, 0.8296, 0.7807,  ..., 0.7050, 0.0257, 0.3558],
         [0.5723, 0.1691, 0.4788,  ..., 0.4936, 0.0378, 0.

In [ ]:
x_original[0,0,0] = 12345
x_original[0,0,0] , x_permuted[0,0,0]

(tensor(12345.), tensor(12345.))

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [ ]:
#Create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
#Lets index on the middle bracket(dim=1)
x[0][0]

tensor([1, 2, 3])

In [ ]:
#lets index on the most inner bracket (last dimension)
x[0][2][2]

tensor(9)

In [ ]:
# You can also use ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
#Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
#Get all values of 0th but only the 1 index value of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [ ]:
#get index 0 and 0th and 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [ ]:
#index on x to return 9
print(x[:,2,2])

#index on x to return 3,6,9
print(x[:,:,2])

tensor([9])
tensor([[3, 6, 9]])


## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [ ]:
#NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) #warning :when converting from numpy -> pytorch reflects numpy deafult datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
#Change the value of array, what will this do tho `tensor`?

array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
#Tensor to NumPy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor


(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Change the tensor , what happends to numpy_tensor?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (try to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better reperesentation of data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seeds**

Essentially what the random seed does is "flavour" the randomness.

In [ ]:
torch.rand(3,3)

tensor([[0.4089, 0.2909, 0.8982],
        [0.6563, 0.8190, 0.9029],
        [0.7826, 0.5677, 0.9412]])

In [ ]:
import torch

#Create two random tensor
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.7180, 0.6308, 0.4577, 0.4554],
        [0.5785, 0.7565, 0.5082, 0.4206],
        [0.7278, 0.9584, 0.9811, 0.9930]])
tensor([[0.8447, 0.8347, 0.2368, 0.0360],
        [0.1296, 0.9927, 0.8961, 0.0230],
        [0.6409, 0.9119, 0.0247, 0.2562]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
#Lets make some random but reproducible tensors
import torch
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPU = faster computation on numbers, CUDA + NVIDIA Hardware + PyTorch

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [ ]:
# Create a tensor
tensor = torch.tensor([1,2,3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
#Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])